version: "3.3"

services:
  Engine:
    restart: always
    image: 2mmilab/hive5-engine
    network_mode: host
    environment:
      - ASPNETCORE_URLS=http://*:9001
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  StreamHub:
    restart: always
    image: 2mmilab/hive5-streamhub
    ports:
      - "9000:8080" 
    environment:
      #- SIGNALR_URL=http://localhost:9000
      - DetailedErrors=true
      #- ASPNETCORE_URLS=http://*:9000
    logging:
      options:
        max-size: "10m"
        max-file: "10"
