services:
  Engine:
    restart: always
    image: 2mmilab/hive5-engine:latest
    network_mode: host
    environment:
      - ASPNETCORE_URLS=http://*:9001
      - ENGINE_BASE_PATH=/app/data/engine
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - /opt/Hive5Data/Engine:/app/data/engine
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: [ "dotnet", "Engine.dll" ]


  StreamHub:
    restart: always
    image: 2mmilab/hive5-streamhub:latest
    ports:
      - "9000:8080" 
    environment:
      - STREAMHUB_BASE_PATH=/app/data/streamhub
    volumes:
      - /opt/Hive5Data/StreamHub:/app/data/streamhub
    logging:
      options:
        max-size: "10m"
        max-file: "10"
    command: [ "dotnet", "Streamhub.dll" ]

